version: "3.9"

services:
  db:
    image: keinos/sqlite3:latest
    container_name: forum-db
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - forum_db:/data
    networks:
      - forum-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: forum-backend
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_PATH: ./DBPath/forum.db
      DB_MAX_CONNECTIONS: 10
      FRONTEND_BASE_URL: http://localhost:3000
      BACKEND_BASE_URL: http://localhost:8080
      ALLOWED_ORIGINS: http://localhost:3000,http://frontend:3000
    volumes:
      - forum_db:/app/DBPath
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - forum-net
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: forum-frontend
    environment:
      PORT: ":3000"
      BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - forum-net

volumes:
  forum_db:

networks:
  forum-net:
